import type { Template } from "@/entities/template";
/**
 * Single `{{ … }}` block for result view resolution (must not contain `}}` before the closing delimiter).
 */
const AGENT_SPELL_REVIEW_HANDOFF_RESULT_DATA = [
  "{{ (() => {",
  "  try {",
  "    const BR = String.fromCharCode(10);",
  "    const step = previous_commits;",
  '    if (!step || typeof step !== "object" || Array.isArray(step)) return "";',
  "    const prs = Array.isArray(step.previous_commits) ? step.previous_commits : [];",
  "    const lines = [];",
  '    lines.push("### Development Stage");',
  '    lines.push("");',
  '    lines.push("#### Preparation");',
  '    lines.push("- LIST every commit since the last externally reviewed spell:");',
  "    const esc = (s) => String(s).split(String.fromCharCode(96)).join(String.fromCharCode(39));",
  "    const bt = String.fromCharCode(96);",
  "    const shortFromUrl = (u) => {",
  "      const s = String(u);",
  '      const ix = s.toLowerCase().indexOf("/commit/");',
  '      if (ix < 0) return "unknown";',
  '      const hex = s.slice(ix + 8).replace(/[^a-fA-F0-9].*/, "");',
  '      return hex.slice(0, 7) || "unknown";',
  "    };",
  "    for (const row of prs) {",
  '      if (!row || typeof row !== "object") continue;',
  "      const r = row;",
  '      const url = String(r.value ?? r.commit_url ?? "").trim();',
  "      const has =",
  "        url ||",
  "        r.content_matches_description === true ||",
  "        r.no_security_changes === true ||",
  '        String(r.comment ?? "").trim();',
  "      if (!has) continue;",
  '      const short = url ? shortFromUrl(url) : "_______";',
  '      const safe = url',
  '        .replace(/\\(/g, "%28")',
  '        .replace(/\\)/g, "%29")',
  '        .replace(/ /g, "%20");',
  '      const link = url ? "[open commit](" + safe + ")" : "(no URL)";',
  '      lines.push("  - " + String.fromCharCode(96) + short + String.fromCharCode(96) + ", " + link);',
  "      const cm = r.content_matches_description === true;",
  '      lines.push("    - [" + (cm ? "x" : " ") + "] Content matches description: no unrelated changes.");',
  '      const com = String(r.comment ?? "").trim();',
  "      if (com) {",
  "        const parts = com.split(/[\\r\\n]+/);",
  "        for (let i = 0; i < parts.length; i++) {",
  '          lines.push((i === 0 ? "      :information_source: " : "            ") + esc(parts[i]));',
  "        }",
  "      }",
  "      const ns = r.no_security_changes === true;",
  '      lines.push("    - [" + (ns ? "x" : " ") + "] No security-related changes are present in this commit.");',
  "    }",
  '    lines.push("");',
  "    const solc = step.solc_version_verified === true;",
  '    lines.push(',
  '      "- [" + (solc ? "x" : " ") + "] Verify solc version matches the Prime Agent protocol standard based on prior contracts."',
  "    );",
  '    const sc = String(step.solc_version_verified_comment ?? "").trim();',
  "    if (sc) {",
  "      const parts = sc.split(/[\\r\\n]+/);",
  "      for (let i = 0; i < parts.length; i++) {",
  '        lines.push((i === 0 ? "  :information_source: " : "        ") + esc(parts[i]));',
  "      }",
  "    }",
  '    lines.push("");',
  '    lines.push("#### Spell Description & Comments");',
  "    const sd =",
  "      spell_description_comments &&",
  '      typeof spell_description_comments === "object" &&',
  "      !Array.isArray(spell_description_comments)",
  "        ? spell_description_comments",
  "        : {};",
  "    const pushSdInfo = (key) => {",
  '      const t = String(sd[key] ?? "").trim();',
  "      if (!t) return;",
  "      const parts = t.split(/[\\r\\n]+/);",
  "      for (let i = 0; i < parts.length; i++) {",
  '        lines.push((i === 0 ? "  :information_source: " : "            ") + esc(parts[i]));',
  "      }",
  "    };",
  '    lines.push("- [" + (sd.pr_clear_description === true ? "x" : " ") + "] Spell PR has clear description.");',
  "    pushSdInfo(\"pr_clear_description_comment\");",
  '    lines.push("- [" + (sd.contract_clear_description === true ? "x" : " ") + "] Spell contract has a clear description.");',
  "    pushSdInfo(\"contract_clear_description_comment\");",
  '    lines.push(',
  '      "- [" +',
  '        (sd.actions_parameters_commented === true ? "x" : " ") +',
  '        "] Every significant action and parameter change is clearly commented in the code."',
  "    );",
  "    pushSdInfo(\"actions_parameters_commented_comment\");",
  '    lines.push(',
  '      "- [" +',
  '        (sd.significant_actions_source_urls === true ? "x" : " ") +',
  '        "] Every significant action has a valid source url (forum post, poll, atlas)."',
  "    );",
  "    pushSdInfo(\"significant_actions_source_urls_comment\");",
  '    lines.push(',
  '      "- [" +',
  '        (sd.parameter_before_after_met === true ? "x" : " ") +',
  '        "] Every parameter change is clearly commented with before/after values."',
  "    );",
  "    pushSdInfo(\"parameter_before_after_comment\");",
  '    lines.push("");',
  '    lines.push("#### Proposed changes");',
  "    const pc =",
  "      spell_proposed_changes &&",
  '      typeof spell_proposed_changes === "object" &&',
  "      !Array.isArray(spell_proposed_changes)",
  "        ? spell_proposed_changes",
  "        : {};",
  "    const pushPcInfo = (key) => {",
  '      const t = String(pc[key] ?? "").trim();',
  "      if (!t) return;",
  "      const parts = t.split(/[\\r\\n]+/);",
  "      for (let i = 0; i < parts.length; i++) {",
  '        lines.push((i === 0 ? "  :information_source: " : "            ") + esc(parts[i]));',
  "      }",
  "    };",
  '    lines.push(',
  '      "- LIST every forum post proposing changes for this particular Star, particular target date:"',
  "    );",
  "    const forumRows = Array.isArray(pc.proposed_change_forum_posts)",
  "      ? pc.proposed_change_forum_posts",
  "      : [];",
  "    for (const fr of forumRows) {",
  '      if (!fr || typeof fr !== "object") continue;',
  '      const fUrl = String(fr.value ?? "").trim();',
  '      const fTitle = String(fr.post_title ?? "").trim();',
  "      const ft = fr.follows_known_template === true;",
  '      const fcom = String(fr.comment ?? "").trim();',
  "      const hasF = fUrl || fTitle || ft || fcom;",
  "      if (!hasF) continue;",
  "      let fMain = \"\";",
  "      if (fTitle && fUrl) {",
  '        fMain = fTitle + ", " + fUrl;',
  "      } else if (fUrl) {",
  "        fMain = fUrl;",
  "      } else {",
  "        fMain = fTitle;",
  "      }",
  '      lines.push("  - " + (fMain ? fMain : "_(incomplete row)_"));',
  "      lines.push(",
  '        "    - [" +',
  '          (ft ? "x" : " ") +',
  '          "] Forum post follows the [known template](https://docs.google.com/document/d/1vLqeP-zXmxKo2OpoxnL2z0ZczPe4nWN49-3URx-iKVA/edit?tab=t.nkz4n7by2dnh)."',
  "      );",
  "      if (fcom) {",
  "        const parts = fcom.split(/[\\r\\n]+/);",
  "        for (let i = 0; i < parts.length; i++) {",
  '          lines.push((i === 0 ? "    :information_source: " : "            ") + esc(parts[i]));',
  "        }",
  "      }",
  "    }",
  '    lines.push(',
  '      "- [" +',
  '        (pc.spell_matches_forum_posts_scope === true ? "x" : " ") +',
  '        "] Verify spell content matches the combined scope of the forum posts listed above."',
  "    );",
  "    pushPcInfo(\"spell_matches_forum_posts_scope_comment\");",
  '    lines.push(',
  '      "- [" +',
  '        (pc.forum_posts_cover_addresses_limits === true ? "x" : " ") +',
  '        "] Verify forum posts contain all new addresses directly or indirectly used in the spell, their constructor arguments and rate limits."',
  "    );",
  "    pushPcInfo(\"forum_posts_cover_addresses_limits_comment\");",
  "    lines.push(",
  '      "- [" +',
  "        (pc.suggest_office_hours_if_major_external_impact === true ? \"x\" : \" \") +",
  '        "] IF the Star Spell introduces a major change that can affect external parties, suggest Governance Facilitators to set Core Spell office hours to " +',
  "        bt +",
  '        "true" +',
  "        bt +",
  '        "."',
  "    );",
  "    pushPcInfo(\"suggest_office_hours_if_major_external_impact_comment\");",
  '    lines.push("");',
  '    lines.push("#### Contract Structure & Code Quality");',
  "    const cq =",
  "      spell_contract_structure &&",
  '      typeof spell_contract_structure === "object" &&',
  "      !Array.isArray(spell_contract_structure)",
  "        ? spell_contract_structure",
  "        : {};",
  "    const pushCqInfo = (key) => {",
  '      const t = String(cq[key] ?? "").trim();',
  "      if (!t) return;",
  "      const parts = t.split(/[\\r\\n]+/);",
  "      for (let i = 0; i < parts.length; i++) {",
  '        lines.push((i === 0 ? "  :information_source: " : "            ") + esc(parts[i]));',
  "      }",
  "    };",
  '    lines.push(',
  '      "- [" +',
  '        (cq.only_execute_external_nonview === true ? "x" : " ") +',
  '        "] The only external non-view function in the spell contract is " + bt + "execute()" + bt + "."',
  "    );",
  "    pushCqInfo(\"only_execute_external_nonview_comment\");",
  '    lines.push(',
  '      "- [" +',
  '        (cq.no_state_modifiers_after_deploy === true ? "x" : " ") +',
  '        "] There are no methods that can modify contract state after deployment."',
  "    );",
  "    pushCqInfo(\"no_state_modifiers_after_deploy_comment\");",
  '    lines.push(',
  '      "- [" +',
  '        (cq.no_unused_imports_or_symbols === true ? "x" : " ") +',
  '        "] No unused imports, interfaces, methods, or variables."',
  "    );",
  "    pushCqInfo(\"no_unused_imports_or_symbols_comment\");",
  '    lines.push(',
  '      "- [" +',
  '        (cq.function_visibility_explicit === true ? "x" : " ") +',
  '        "] All function visibility modifiers are explicitly declared."',
  "    );",
  "    pushCqInfo(\"function_visibility_explicit_comment\");",
  '    lines.push(',
  '      "- [" +',
  '        (cq.no_redundant_or_commentdead_code === true ? "x" : " ") +',
  '        "] No redundant code or commented-out functionality."',
  "    );",
  "    pushCqInfo(\"no_redundant_or_commentdead_code_comment\");",
  "    lines.push(",
  '      "- [" +',
  "        (cq.addresses_from_registry_or_constant === true ? \"x\" : \" \") +",
  '        "] Addresses must be fetched from the relevant protocol\'s address registry (e.g., " +',
  "        bt +",
  '        "pattern-address-registry" +',
  "        bt +",
  '        ") IF they are present there, OTHERWISE defined as " +',
  "        bt +",
  '        "constant" +',
  "        bt +",
  '        " and have trusted source (e.g., when onboarding new contracts)."',
  "    );",
  "    pushCqInfo(\"addresses_from_registry_or_constant_comment\");",
  "    lines.push(",
  '      "- LIST every address used in the spell (defined as " +',
  "      bt +",
  '      "constant" +',
  "      bt +",
  '      " or fetched from the registry repo):"',
  "    );",
  "    const addrRows = Array.isArray(cq.address_rows) ? cq.address_rows : [];",
  "    for (const ar of addrRows) {",
  '      if (!ar || typeof ar !== "object") continue;',
  '      const addr = String(ar.value ?? "").trim();',
  '      const reg = String(ar.registry_label ?? "").trim();',
  '      const src = String(ar.source_url ?? "").trim();',
  "      const m = ar.matches_valid_external_source === true;",
  '      const acom = String(ar.comment ?? "").trim();',
  "      const hasAddr = addr || reg || src || m || acom;",
  "      if (!hasAddr) continue;",
  "      let main = \"\";",
  "      if (reg && addr) {",
  '        main = reg + " " + bt + addr + bt;',
  "      } else if (reg) {",
  "        main = reg;",
  "      } else if (addr) {",
  '        main = bt + addr + bt;',
  "      }",
  "      if (src) {",
  '        main = main ? main + ", " + src : src;',
  "      }",
  '      lines.push("  - " + (main ? main : "_(incomplete row)_"));',
  "      lines.push(",
  '        "    - [" +',
  '          (m ? "x" : " ") +',
  '          "] Matches valid external source (previously approved forum post, external docs, etc)."',
  "      );",
  "      if (acom) {",
  "        const parts = acom.split(/[\\r\\n]+/);",
  "        for (let i = 0; i < parts.length; i++) {",
  '          lines.push((i === 0 ? "      :information_source: " : "            ") + esc(parts[i]));',
  "        }",
  "      }",
  "    }",
  '    lines.push("");',
  "    const pick = (v) =>",
  '      v && typeof v === "object" && !Array.isArray(v) ? v : {};',
  "    const pi2 = (o, k) => {",
  '      const t = String(o[k] ?? "").trim();',
  "      if (!t) return;",
  "      const ps = t.split(/[\\r\\n]+/);",
  "      for (let i = 0; i < ps.length; i++) {",
  '        lines.push((i === 0 ? "  :information_source: " : "            ") + esc(ps[i]));',
  "      }",
  "    };",
  "    const pi4 = (o, k) => {",
  '      const t = String(o[k] ?? "").trim();',
  "      if (!t) return;",
  "      const ps = t.split(/[\\r\\n]+/);",
  "      for (let i = 0; i < ps.length; i++) {",
  '        lines.push((i === 0 ? "    :information_source: " : "            ") + esc(ps[i]));',
  "      }",
  "    };",
  "    const piWarn2 = (o, k) => {",
  '      const t = String(o[k] ?? "").trim();',
  "      if (!t) return;",
  "      const ps = t.split(/[\\r\\n]+/);",
  "      for (let i = 0; i < ps.length; i++) {",
  '        lines.push((i === 0 ? "  :warning: " : "            ") + esc(ps[i]));',
  "      }",
  "    };",
  '    lines.push("#### StarGuard execution");',
  "    const sg = pick(spell_starguard);",
  "    lines.push(",
  '      "- [" +',
  '        (sg.sg_onboarded === true ? "x" : " ") +',
  '        "] IF a [StarGuard module](https://github.com/sky-ecosystem/star-guard) is onboarded for this Star, the following additional checks are done:"',
  "    );",
  "    pi2(sg, \"sg_onboarded_comment\");",
  '    lines.push("  - [" + (sg.sg_executable_view === true ? "x" : " ") + "] The spell exposes view-only interface " + bt + "function isExecutable() external view returns (bool result)" + bt + ".");',
  "    pi4(sg, \"sg_executable_view_comment\");",
  '    lines.push("  - [" + (sg.sg_executable_logic_ok === true ? "x" : " ") + "] " + bt + "isExecutable" + bt + " either simply returns " + bt + "true" + bt + " or implements additional logic communicated via the relevant forum post (e.g., by describing \\"earliest launch date\\" or \\"office hours\\" logic, etc).");',
  "    pi4(sg, \"sg_executable_logic_comment\");",
  '    lines.push("  - [" + (sg.sg_test_executable_before_expiry === true ? "x" : " ") + "] The test ensures the spell is executable before expiration (i.e. " + bt + "isExecutable" + bt + " outputs " + bt + "true" + bt + " before " + bt + "StarGuard.maxDelay()" + bt + " is passed).");',
  "    pi4(sg, \"sg_test_executable_before_expiry_comment\");",
  '    lines.push("  - [" + (sg.sg_third_party_later_block === true ? "x" : " ") + "] Third-party actors can not take advantage of the fact that Spell will be executed in a later block than the Core spell, otherwise suggest " + bt + "direct execution" + bt + ".");',
  "    pi4(sg, \"sg_third_party_later_block_comment\");",
  '    lines.push("  - [" + (sg.sg_sequential_forum_direct_exec === true ? "x" : " ") + "] IF Star spell can not be executed in a later block OR have to be executed sequentially to another Star spell, " + bt + "direct execution" + bt + " is clearly mentioned in the forum post together with elaborated explanation why it is needed.");',
  "    pi4(sg, \"sg_sequential_forum_direct_exec_comment\");",
  "    if (sg.sg_direct_exec_technical_strike === true) {",
  '      lines.push("  - ~~[ ] The " + bt + "direct execution" + bt + " explanation makes sense on the technical level and can not be circumvented by the use of " + bt + "isExecutable()" + bt + " interface.~~");',
  "    } else {",
  '      lines.push("  - [" + (sg.sg_direct_exec_technical_met === true ? "x" : " ") + "] The " + bt + "direct execution" + bt + " explanation makes sense on the technical level and can not be circumvented by the use of " + bt + "isExecutable()" + bt + " interface.");',
  "    }",
  "    pi4(sg, \"sg_direct_exec_technical_comment\");",
  "    pi2(sg, \"sg_block_footer\");",
  '    lines.push("");',
  '    lines.push("#### On-boarding New Contracts");',
  "    const ob = pick(spell_new_contracts);",
  '    lines.push("- LIST every new contract present in the spell:");',
  "    const ncr = Array.isArray(ob.new_contract_rows) ? ob.new_contract_rows : [];",
  "    for (const cr of ncr) {",
  '      if (!cr || typeof cr !== "object") continue;',
  '      const ex = String(cr.value ?? "").trim();',
  '      const hd = String(cr.contract_heading ?? "").trim();',
  '      const hx = String(cr.address_hex ?? "").trim();',
  "      const h = cr.source_explorer_verified === true;",
  "      const g = cr.source_matches_audited_repo === true;",
  "      const cmp = cr.compilation_matches_repo === true;",
  "      const lic = cr.consistent_license === true;",
  '      const tail = String(cr.constructor_and_access_markdown ?? "").trim();',
  "      const has = ex || hd || hx || h || g || cmp || lic || tail;",
  "      if (!has) continue;",
  "      let top = \"\";",
  "      if (hd && hx && ex) {",
  '        top = hd + ", [" + hx + "](" + ex + ")";',
  "      } else if (hd && hx) {",
  '        top = hd + ", " + bt + hx + bt;',
  "      } else {",
  '        top = hd || (hx ? bt + hx + bt : "") || ex || "_(incomplete row)_";',
  "      }",
  '      lines.push("  - " + top);',
  '      lines.push("    - [" + (h ? "x" : " ") + "] Source code is verified on Etherscan or other primary block explorer for this chain.");',
  "      pi4(cr, \"source_explorer_verified_comment\");",
  '      lines.push("    - [" + (g ? "x" : " ") + "] Source code matches corresponding audited GitHub source code.");',
  "      pi4(cr, \"source_matches_audited_repo_comment\");",
  '      lines.push("    - [" + (cmp ? "x" : " ") + "] Compilation optimizations match deployment settings defined in the source code repo.");',
  "      pi4(cr, \"compilation_matches_repo_comment\");",
  '      lines.push("    - [" + (lic ? "x" : " ") + "] Consistent license.");',
  "      pi4(cr, \"consistent_license_comment\");",
  "      if (tail) {",
  "        for (const ln of tail.split(/[\\r\\n]+/)) {",
  '          const s = String(ln).replace(/[\\t ]+$/, "");',
  "          if (s.trim()) lines.push(s);",
  "        }",
  "      }",
  "    }",
  '    lines.push("");',
  '    lines.push("#### Dependency checks");',
  "    const dp = pick(spell_dependency_checks);",
  "    const subs = Array.isArray(dp.submodule_listing) ? dp.submodule_listing : [];",
  '    const sm = String(dp.submodule_listing_block ?? "").trim();',
  "    const repoRootFromCommitUrl = (u) => {",
  "      const s = String(u);",
  '      const ix = s.toLowerCase().indexOf("/commit/");',
  "      if (ix < 0) return \"\";",
  "      return s.slice(0, ix);",
  "    };",
  "    if (subs.length > 0) {",
  '      lines.push("- LIST every submodule or any other imported code used in this spell:");',
  '      lines.push("  ```");',
  "      for (const srow of subs) {",
  '        if (!srow || typeof srow !== "object") continue;',
  '        const sp = String(srow.value ?? "").trim();',
  '        const sc = String(srow.commit ?? "").trim();',
  "        if (sp || sc) {",
  '          lines.push("  " + (sc && sp ? sc + " " + sp : sp || sc));',
  "        }",
  "      }",
  '      lines.push("  ```");',
  "      for (const srow of subs) {",
  '        if (!srow || typeof srow !== "object") continue;',
  '        const sp = String(srow.value ?? "").trim();',
  '        const cRaw = String(srow.commit ?? "").trim();',
  '        const depCom = String(srow.commit_match_deployment_comment ?? "").trim();',
  "        const aud = srow.commit_match === true;",
  "        const dep = srow.commit_match_deployment === true;",
  "        if (!sp && !cRaw && !depCom && !aud && !dep) continue;",
  "        let commitMd = \"\";",
  "        if (/^https?:\\/\\//i.test(cRaw)) {",
  '          const sh = shortFromUrl(cRaw);',
  '          const safe = cRaw.replace(/\\(/g, "%28").replace(/\\)/g, "%29").replace(/ /g, "%20");',
  '          commitMd = "[" + bt + sh + bt + "](" + safe + ")";',
  "        } else if (cRaw) {",
  '          commitMd = bt + cRaw + bt;',
  "        }",
  "        const root = cRaw ? repoRootFromCommitUrl(cRaw) : \"\";",
  "        let lead = \"\";",
  "        if (sp && cRaw) {",
  '          lead = bt + sp + bt + " imported at commit " + commitMd;',
  "        } else if (sp) {",
  "          lead = bt + sp + bt;",
  "        } else {",
  "          lead = commitMd;",
  "        }",
  '        lines.push("  - " + (lead || "_(incomplete row)_") + (root ? " " + root : ""));',
  '        lines.push("    - [" + (aud ? "x" : " ") + "] The dependency commit matches audited commit.");',
  "        if (dep) {",
  '          lines.push("    - [x] The dependency commit matches the version of the deployed contracts.");',
  "        } else {",
  '          lines.push("    - ~~[ ] The dependency commit matches the version of the deployed contracts.~~");',
  "        }",
  "        if (depCom) {",
  "          const ps = depCom.split(/[\\r\\n]+/);",
  "          for (let i = 0; i < ps.length; i++) {",
  '            lines.push((i === 0 ? "    :information_source: " : "            ") + esc(ps[i]));',
  "          }",
  "        }",
  "      }",
  "    } else {",
  "      if (sm) {",
  '        lines.push("- LIST every submodule or any other imported code used in this spell:");',
  '        lines.push("  ```");',
  "        for (const ln of sm.split(/[\\r\\n]+/)) {",
  '          lines.push("  " + ln);',
  "        }",
  '        lines.push("  ```");',
  "      }",
  "      const drs = Array.isArray(dp.dependency_rows) ? dp.dependency_rows : [];",
  "      for (const dr of drs) {",
  '        if (!dr || typeof dr !== "object") continue;',
  '        const u = String(dr.value ?? "").trim();',
  '        const lead = String(dr.dependency_lead ?? "").trim();',
  "        const has = u || lead || dr.dep_matches_audited === true || dr.dep_audit_na === true || dr.dep_matches_deployed === true || dr.dep_deploy_strike === true;",
  '        const com = String(dr.comment ?? "").trim();',
  "        if (!has && !com) continue;",
  '        lines.push("  - " + (lead ? lead + (u ? ", " + u : "") : u || "_(incomplete row)_"));',
  "        if (dr.dep_audit_na === true) {",
  '          lines.push("    - **N/A** The dependency commit matches audited commit.");',
  "        } else {",
  '          lines.push("    - [" + (dr.dep_matches_audited === true ? "x" : " ") + "] The dependency commit matches audited commit.");',
  "        }",
  "        pi4(dr, \"dep_audited_comment\");",
  "        if (dr.dep_deploy_strike === true) {",
  '          lines.push("    - ~~[ ] The dependency commit matches the version of the deployed contracts.~~");',
  "        } else {",
  '          lines.push("    - [" + (dr.dep_matches_deployed === true ? "x" : " ") + "] The dependency commit matches the version of the deployed contracts.");',
  "        }",
  "        pi4(dr, \"comment\");",
  "      }",
  "    }",
  '    lines.push("");',
  '    lines.push("#### Interfaces");',
  "    const inf = pick(spell_interfaces);",
  '    lines.push("- [" + (inf.intf_no_unused_static === true ? "x" : " ") + "] No unused static interfaces.");',
  "    pi2(inf, \"intf_no_unused_static_comment\");",
  '    lines.push("- [" + (inf.intf_stdlib_or_import === true ? "x" : " ") + "] Declared static interface is not present in standard libraries, OTHERWISE should be imported from there.");',
  "    pi2(inf, \"intf_stdlib_or_import_comment\");",
  '    lines.push("- [" + (inf.intf_matches_deployed === true ? "x" : " ") + "] Interface matches the deployed contract.");',
  "    pi2(inf, \"intf_matches_deployed_comment\");",
  '    lines.push("- [" + (inf.intf_only_used_functions === true ? "x" : " ") + "] Each static interface declares only functions actually used in the spell code.");',
  "    pi2(inf, \"intf_only_used_functions_comment\");",
  '    lines.push("");',
  '    lines.push("#### Variable Declarations");',
  "    const vd = pick(spell_variable_declarations);",
  '    lines.push("- [" + (vd.vd_constants_or_immutable === true ? "x" : " ") + "] Every contract variable is declared as either " + bt + "constant" + bt + " or " + bt + "immutable" + bt + ".");',
  "    pi2(vd, \"vd_constants_or_immutable_comment\");",
  '    lines.push("- [" + (vd.vd_precision_literals_ok === true ? "x" : " ") + "] Every precision variable (" + bt + "WAD" + bt + ", " + bt + "RAY" + bt + ", " + bt + "RAD" + bt + ", etc) match their expected value.");',
  "    pi2(vd, \"vd_precision_literals_ok_comment\");",
  '    lines.push("- LIST every variable using precision (" + bt + "e18" + bt + ", " + bt + "e6" + bt + ", " + bt + "e..." + bt + ", " + bt + "WAD" + bt + ", " + bt + "RAY" + bt + ", " + bt + "RAD" + bt + ", etc):");',
  "    const vdPrecRows = Array.isArray(vd.precision_variable_rows) ? vd.precision_variable_rows : [];",
  "    for (const pr of vdPrecRows) {",
  '      if (!pr || typeof pr !== "object") continue;',
  '      const vName = String(pr.value ?? "").trim();',
  '      const ptxt = String(pr.precision_text ?? "").trim();',
  '      const purl = String(pr.precision_url ?? "").trim();',
  "      const ok = pr.precision_matches_source === true;",
  '      const prc = String(pr.comment ?? "").trim();',
  "      if (!vName && !ptxt && !purl && !prc && !ok) continue;",
  "      let prow = \"\";",
  "      if (vName && ptxt) {",
  '        prow = bt + vName + bt + " with precision " + bt + ptxt + bt + (purl ? ", " + purl : "");',
  "      } else if (vName) {",
  '        prow = bt + vName + bt + (purl ? ", " + purl : "");',
  "      } else {",
  '        prow = ptxt + (purl ? ", " + purl : "") || "_(incomplete row)_";',
  "      }",
  '      lines.push("  - " + prow);',
  '      lines.push("    - [" + (ok ? "x" : " ") + "] The precision matches provided source url.");',
  "      if (prc) {",
  "        const ps = prc.split(/[\\r\\n]+/);",
  "        for (let i = 0; i < ps.length; i++) {",
  '          lines.push((i === 0 ? "      :information_source: " : "            ") + esc(ps[i]));',
  "        }",
  "      }",
  "    }",
  '    lines.push("- [" + (vd.vd_rates_slash_days_ok === true ? "x" : " ") + "] Rates are expressed correctly (e.g. per " + bt + "/ 1 days" + bt + ").");',
  "    pi2(vd, \"vd_rates_slash_days_comment\");",
  '    lines.push("- [" + (vd.vd_rates_match_source === true ? "x" : " ") + "] Rates match their source (e.g., governance poll).");',
  "    pi2(vd, \"vd_rates_match_source_comment\");",
  '    lines.push("- [" + (vd.vd_timestamps_utc_ok === true ? "x" : " ") + "] Timestamps are commented with the full UTC date and convert correctly.");',
  "    pi2(vd, \"vd_timestamps_utc_comment\");",
  '    lines.push("- [" + (vd.vd_timestamps_match_source === true ? "x" : " ") + "] Timestamps match their source (e.g., governance poll).");',
  "    pi2(vd, \"vd_timestamps_match_source_comment\");",
  '    lines.push("");',
  '    lines.push("#### Deployment & Execution Security");',
  "    const ds = pick(spell_deployment_security);",
  '    lines.push("- [" + (ds.ds_no_selfdestruct === true ? "x" : " ") + "] No " + bt + "selfdestruct()" + bt + " operations in the spell.");',
  "    pi2(ds, \"ds_no_selfdestruct_comment\");",
  '    lines.push("- [" + (ds.ds_no_delegatecall_untrusted === true ? "x" : " ") + "] No " + bt + "delegatecall()" + bt + " to untrusted contracts.");',
  "    pi2(ds, \"ds_no_delegatecall_untrusted_comment\");",
  '    lines.push("- [" + (ds.ds_no_tx_origin_auth === true ? "x" : " ") + "] No use of " + bt + "tx.origin" + bt + " for authorization.");',
  "    pi2(ds, \"ds_no_tx_origin_auth_comment\");",
  '    lines.push("- [" + (ds.ds_no_external_revert_spell === true ? "x" : " ") + "] No external calls that could revert and fail the entire spell execution.");',
  "    pi2(ds, \"ds_no_external_revert_spell_comment\");",
  '    lines.push("- [" + (ds.ds_no_unbounded_loops === true ? "x" : " ") + "] No loops with unbounded gas consumption.");',
  "    pi2(ds, \"ds_no_unbounded_loops_comment\");",
  '    lines.push("- [" + (ds.ds_no_timestamp_gsm_issues === true ? "x" : " ") + "] No timestamp-dependent logic that could cause issues across the GSM delay.");',
  "    pi2(ds, \"ds_no_timestamp_gsm_issues_comment\");",
  '    lines.push("- [" + (ds.ds_safe_math_or_checked === true ? "x" : " ") + "] All math operations use safe math libraries or are checked for overflow/underflow.");',
  "    pi2(ds, \"ds_safe_math_or_checked_comment\");",
  '    lines.push("- [" + (ds.ds_no_ignored_return_values === true ? "x" : " ") + "] No unchecked return values from external calls.");',
  "    pi2(ds, \"ds_no_ignored_return_values_comment\");",
  '    lines.push("");',
  '    lines.push("#### Access Control");',
  "    const ac = pick(spell_access_control);",
  '    lines.push("- [" + (ac.ac_no_frontrun_execution === true ? "x" : " ") + "] Spell execution cannot be front-run by malicious actors.");',
  "    pi2(ac, \"ac_no_frontrun_execution_comment\");",
  "    if (ac.ac_privileged_strike === true) {",
  '      lines.push("- [ ] ~~No privileged functions accessible by unauthorized users.~~");',
  "    } else {",
  '      lines.push("- [" + (ac.ac_no_unauthorized_privileged === true ? "x" : " ") + "] No privileged functions accessible by unauthorized users.");',
  "    }",
  "    pi2(ac, \"ac_privileged_comment\");",
  '    lines.push("");',
  '    lines.push("#### Parameter Changes & Protocol Integration");',
  "    const pp = pick(spell_parameter_protocol);",
  '    lines.push("- [" + (pp.pp_star_invariants === true ? "x" : " ") + "] Star Protocol invariants are maintained after spell execution.");',
  "    pi2(pp, \"pp_star_invariants_comment\");",
  '    lines.push("- [" + (pp.pp_helpers_used === true ? "x" : " ") + "] All parameter changes use the appropriate helper functions IF available.");',
  "    pi2(pp, \"pp_helpers_used_comment\");",
  '    lines.push("- [" + (pp.pp_matches_executive_or_atlas === true ? "x" : " ") + "] Parameter changes match the Executive Sheet or the corresponding Atlas edit exactly.");',
  "    piWarn2(pp, \"pp_matches_executive_or_atlas_comment\");",
  '    lines.push("- [" + (pp.pp_protocol_integration_ok === true ? "x" : " ") + "] Spell interacts correctly with existing protocol components.");',
  "    pi2(pp, \"pp_protocol_integration_ok_comment\");",
  '    lines.push("- [" + (pp.pp_error_handling_ok === true ? "x" : " ") + "] Proper error handling for all external interactions.");',
  "    pi2(pp, \"pp_error_handling_ok_comment\");",
  '    lines.push("");',
  '    lines.push("#### Testing");',
  "    const tt = pick(spell_testing_review);",
  '    lines.push("- LIST each spell action (each line of code which changes a storage):");',
  "    const trows = Array.isArray(tt.spell_action_test_rows) ? tt.spell_action_test_rows : [];",
  "    for (const tr of trows) {",
  '      if (!tr || typeof tr !== "object") continue;',
  '      const act = String(tr.value ?? "").trim();',
  "      const uok = tr.unit_test_value_changed === true;",
  "      const eok = tr.e2e_test_sufficient === true;",
  '      const uc = String(tr.unit_test_comment ?? "").trim();',
  '      const ec = String(tr.e2e_test_comment ?? "").trim();',
  "      if (!act && !uok && !eok && !uc && !ec) continue;",
  '      lines.push("  - " + (act || "_(incomplete row)_"));',
  '      lines.push("    - [" + (uok ? "x" : " ") + "] The unit test ensures the new value was changed in the spell.");',
  "      if (uc) {",
  "        const ps = uc.split(/[\\r\\n]+/);",
  "        for (let i = 0; i < ps.length; i++) {",
  '          lines.push((i === 0 ? "      :information_source: " : "            ") + esc(ps[i]));',
  "        }",
  "      }",
  '      lines.push("    - [" + (eok ? "x" : " ") + "] The end-to-end test is sufficient to ensure correctness the high-level goal behind this spell action.");',
  "      if (ec) {",
  "        const ps = ec.split(/[\\r\\n]+/);",
  "        for (let i = 0; i < ps.length; i++) {",
  '          lines.push((i === 0 ? "      :information_source: " : "            ") + esc(ps[i]));',
  "        }",
  "      }",
  "    }",
  '    lines.push("- [" + (tt.test_all_actions_covered === true ? "x" : " ") + "] All actions are covered by tests.");',
  "    pi2(tt, \"test_all_actions_covered_comment\");",
  '    lines.push("- [" + (tt.test_integration_flow === true ? "x" : " ") + "] Integration tests verify the end-to-end execution flow.");',
  "    pi2(tt, \"test_integration_flow_comment\");",
  '    lines.push("- [" + (tt.test_gas_within_block_limit === true ? "x" : " ") + "] Gas tests ensure execution is possible within the existing block gas limit.");',
  "    pi2(tt, \"test_gas_within_block_limit_comment\");",
  "    {",
  '      const rawCi = String(tt.test_ci_passing_comment ?? "").trim();',
  "      const ciParts = rawCi ? rawCi.split(/[\\r\\n]+/) : [];",
  '      const ciFirst = ciParts.length ? String(ciParts[0] ?? "").trim() : "";',
  "      const ciRest = ciParts.slice(1).join(BR).trim();",
  '      let ciTail = "the referenced commit";',
  "      if (ciFirst) {",
  "        ciTail = ciFirst;",
  "        if (!/[.]$/.test(ciTail)) {",
  '          ciTail = ciTail + ".";',
  "        }",
  "      }",
  '      lines.push("- [" + (tt.test_ci_passing_at_sha === true ? "x" : " ") + "] All tests are passing in CI at " + ciTail);',
  "      if (ciRest) {",
  "        const ps = ciRest.split(/[\\r\\n]+/);",
  "        for (let i = 0; i < ps.length; i++) {",
  '          lines.push((i === 0 ? "  :information_source: " : "            ") + esc(ps[i]));',
  "        }",
  "      }",
  "    }",
  '    lines.push("- [" + (tt.test_none_skipped === true ? "x" : " ") + "] All tests listed above are not " + bt + "skipped" + bt + ".");',
  "    pi2(tt, \"test_none_skipped_comment\");",
  "    {",
  '      const locRaw = String(tt.test_local_output_block ?? "").trim();',
  "      if (locRaw) {",
  "        const locLines = locRaw.split(/[\\r\\n]+/);",
  '        const locHead = String(locLines[0] ?? "").trim();',
  '        let localRef = "the referenced revision";',
  "        let locFence = locRaw;",
  "        if (/^[0-9a-f]{7,40}$/i.test(locHead)) {",
  "          localRef = bt + locHead + bt;",
  "          locFence = locLines.slice(1).join(BR).trim();",
  "        }",
  '        lines.push("- [" + (tt.test_local_passing === true ? "x" : " ") + "] All tests are passing locally at " + localRef + ":");',
  '        lines.push("");',
  '        lines.push("```");',
  "        for (const ln of locFence.split(/[\\r\\n]+/)) {",
  "          lines.push(ln);",
  "        }",
  '        lines.push("```");',
  "      }",
  "    }",
  "    pi2(tt, \"test_post_output_comment\");",
  '    lines.push("");',
  '    lines.push("#### Pre-Deployment checks");',
  "    const pre = pick(spell_pre_deployment);",
  '    lines.push("- [" + (pre.pre_exec_sheet_matches_scope === true ? "x" : " ") + "] Actions listed in the [Executive Sheet](https://docs.google.com/spreadsheets/d/1w_z5WpqxzwreCcaveB2Ye1PP5B8QAHDglzyxKHG3CHw/edit) for this Star match the spell scope.");',
  "    pi2(pre, \"pre_exec_sheet_matches_scope_comment\");",
  '    lines.push("  - [" + (pre.pre_exec_sheet_not_ready_alt === true ? "x" : " ") + "] IF Executive Sheet is not yet ready at the time of review, reference [the corresponding Atlas edit weekly proposal](https://forum.sky.money/tag/atlas-edit-weekly-proposal) and [FORUM POST](https://forum.skyeco.com/t/proposed-changes-to-pattern-for-upcoming-spell/27835).");',
  "    pi2(pre, \"pre_exec_sheet_not_ready_alt_comment\");",
  '    lines.push("- [" + (pre.pre_instruction_text_in_spell === true ? "x" : " ") + "] Every _Instruction text_ from the Executive Sheet is copied to the spell code as a comment.");',
  "    pi2(pre, \"pre_instruction_text_in_spell_comment\");",
  '    lines.push("  - [" + (pre.pre_instruction_not_ready_alt === true ? "x" : " ") + "] IF Executive Sheet is not yet ready at the time of review, reference [the corresponding Atlas edit weekly proposal](https://forum.sky.money/tag/atlas-edit-weekly-proposal) and [FORUM POST](https://forum.skyeco.com/t/proposed-changes-to-pattern-for-upcoming-spell/27835).");',
  "    pi2(pre, \"pre_instruction_not_ready_alt_comment\");",
  '    lines.push("- [" + (pre.pre_instruction_cannot_note === true ? "x" : " ") + "] IF an instruction cannot be taken, it should have an explanation under the instruction prefixed with " + bt + "// Note:" + bt + ".");',
  "    pi2(pre, \"pre_instruction_cannot_note_comment\");",
  '    lines.push("- [" + (pre.pre_unlisted_action_note === true ? "x" : " ") + "] IF an action in the spell doesn\'t have a relevant instruction, its necessity is explained in a comment prefixed with " + bt + "// Note:" + bt + ".");',
  "    pi2(pre, \"pre_unlisted_action_note_comment\");",
  '    lines.push("- [" + (pre.pre_spell_in_exec_sheet === true ? "x" : " ") + "] All actions present in the spell code are present in the final Executive Sheet.");',
  "    pi2(pre, \"pre_spell_in_exec_sheet_comment\");",
  '    lines.push("  - [" + (pre.pre_spell_in_sheet_not_ready_alt === true ? "x" : " ") + "] IF Executive Sheet is not yet ready at the time of review, reference [the corresponding Atlas edit weekly proposal](https://forum.sky.money/tag/atlas-edit-weekly-proposal) and [FORUM POST](https://forum.skyeco.com/t/proposed-changes-to-pattern-for-upcoming-spell/27835).");',
  "    pi2(pre, \"pre_spell_in_sheet_not_ready_alt_comment\");",
  '    lines.push("- [" + (pre.pre_exec_sheet_in_spell === true ? "x" : " ") + "] All actions in the final Executive Sheet are present in the spell code.");',
  "    pi2(pre, \"pre_exec_sheet_in_spell_comment\");",
  '    lines.push("  - [" + (pre.pre_exec_sheet_in_spell_not_ready_alt === true ? "x" : " ") + "] IF Executive Sheet is not yet ready at the time of review, reference [the corresponding Atlas edit weekly proposal](https://forum.sky.money/tag/atlas-edit-weekly-proposal) and [FORUM POST](https://forum.skyeco.com/t/proposed-changes-to-pattern-for-upcoming-spell/27835).");',
  "    pi2(pre, \"pre_exec_sheet_in_spell_not_ready_alt_comment\");",
  '    lines.push("- [" + (pre.pre_reverified_after_commits === true ? "x" : " ") + "] IF new commits were added after the initial review, the relevant checklist items have been re-verified.");',
  "    pi2(pre, \"pre_reverified_after_commits_comment\");",
  '    lines.push("- [" + (pre.pre_good_to_deploy_post === true ? "x" : " ") + "] IF no blockers were found, post the completed \\"Development Stage\\" checklist stage with the explicit \\"Good to deploy\\" note on top.");',
  "    piWarn2(pre, \"pre_good_to_deploy_post_comment\");",
  '    lines.push("");',
  "    return lines.join(BR);",
  "  } catch (e) {",
  '    return "";',
  "  }",
  "})() }}",

].join("\n");

export const agentSpellReviewTemplate: Template = {
  key: "agent-spell-review",
  name: "Agent spell review",
  firstStepKey: "previous_commits",
  permissions: [],
  steps: [
    {
      key: "previous_commits",
      type: "input",
      title: "Review previous commits",
      permissions: [],
      nextStepKey: "spell_description_comments",
      inputs: [
        {
          key: "previous_commits",
          type: "item_list",
          title: "List every commit since the last externally reviewed spell (e.g. https://github.com/grove-labs/grove-spells/commit/da4e38f113c55fcc083fdafe2e8dd39fc0e9f362):",
          subInputs: [
            {
              key: "content_matches_description",
              type: "bool",
              title: "Content matches description",
            },
            {
              key: "no_security_changes",
              type: "bool",
              title: "No security-related changes are present in this commit.",
            },
            {
              key: "comment",
              type: "string",
              title: "Comment (optional)",
            },
          ],
        },
        {
          key: "solc_version_verified",
          type: "bool",
          title:
            "Verify solc version matches the Prime Agent protocol standard based on prior contracts.",
        },
        {
          key: "solc_version_verified_comment",
          type: "string",
          title: "Comment (optional)",
        },
      ],
    },
    {
      key: "spell_description_comments",
      type: "input",
      title: "Spell description and comments",
      permissions: [],
      nextStepKey: "spell_proposed_changes",
      inputs: [
        {
          key: "pr_clear_description",
          type: "bool",
          title: "Spell PR has clear description.",
        },
        {
          key: "pr_clear_description_comment",
          type: "string",
          title: "Notes (optional)",
        },
        {
          key: "contract_clear_description",
          type: "bool",
          title: "Spell contract has a clear description.",
        },
        {
          key: "contract_clear_description_comment",
          type: "string",
          title: "Notes (optional)",
        },
        {
          key: "actions_parameters_commented",
          type: "bool",
          title:
            "Every significant action and parameter change is clearly commented in the code.",
        },
        {
          key: "actions_parameters_commented_comment",
          type: "string",
          title: "Notes (optional)",
        },
        {
          key: "significant_actions_source_urls",
          type: "bool",
          title:
            "Every significant action has a valid source url (forum post, poll, atlas).",
        },
        {
          key: "significant_actions_source_urls_comment",
          type: "string",
          title: "Notes (optional)",
        },
        {
          key: "parameter_before_after_met",
          type: "bool",
          title:
            "Every parameter change is clearly commented with before/after values.",
        },
        {
          key: "parameter_before_after_comment",
          type: "string",
          title: "Notes (optional)",
        },
      ],
    },
    {
      key: "spell_proposed_changes",
      type: "input",
      title: "Proposed changes",
      permissions: [],
      nextStepKey: "spell_contract_structure",
      inputs: [
        {
          key: "proposed_change_forum_posts",
          type: "item_list",
          title:
            "List every forum post proposing changes for this particular Agent & target date (e.g. https://forum.skyeco.com/t/proposed-changes-to-pattern-for-upcoming-spell/27835):",
          subInputs: [
            {
              key: "post_title",
              type: "string",
              title: "Post title / name (e.g. Proposed Changes to Grove for Upcoming Spell)",
            },
            {
              key: "follows_known_template",
              type: "bool",
              title: "Forum post follows the known spell proposal template (Google Doc).",
            },
            {
              key: "comment",
              type: "string",
              title: "Notes (optional)",
            },
          ],
        },
        {
          key: "spell_matches_forum_posts_scope",
          type: "bool",
          title:
            "Verify spell content matches the combined scope of the forum posts listed above.",
        },
        {
          key: "spell_matches_forum_posts_scope_comment",
          type: "string",
          title: "Notes (optional)",
        },
        {
          key: "forum_posts_cover_addresses_limits",
          type: "bool",
          title:
            "Verify forum posts contain all new addresses (direct or indirect), constructor arguments, and rate limits.",
        },
        {
          key: "forum_posts_cover_addresses_limits_comment",
          type: "string",
          title: "Notes (optional)",
        },
        {
          key: "suggest_office_hours_if_major_external_impact",
          type: "bool",
          title:
            "If the Star Spell introduces a major change affecting external parties: suggest Governance Facilitators set Core Spell office hours to `true`.",
        },
        {
          key: "suggest_office_hours_if_major_external_impact_comment",
          type: "string",
          title: "Notes (optional)",
        },
      ],
    },
    {
      key: "spell_contract_structure",
      type: "input",
      title: "Contract structure and code quality",
      permissions: [],
      nextStepKey: "spell_starguard",
      inputs: [
        {
          key: "only_execute_external_nonview",
          type: "bool",
          title:
            "The only external non-view function in the spell contract is `execute()`.",
        },
        {
          key: "only_execute_external_nonview_comment",
          type: "string",
          title: "Notes (optional)",
        },
        {
          key: "no_state_modifiers_after_deploy",
          type: "bool",
          title:
            "There are no methods that can modify contract state after deployment.",
        },
        {
          key: "no_state_modifiers_after_deploy_comment",
          type: "string",
          title: "Notes (optional)",
        },
        {
          key: "no_unused_imports_or_symbols",
          type: "bool",
          title:
            "No unused imports, interfaces, methods, or variables.",
        },
        {
          key: "no_unused_imports_or_symbols_comment",
          type: "string",
          title: "Notes (optional)",
        },
        {
          key: "function_visibility_explicit",
          type: "bool",
          title:
            "All function visibility modifiers are explicitly declared.",
        },
        {
          key: "function_visibility_explicit_comment",
          type: "string",
          title: "Notes (optional)",
        },
        {
          key: "no_redundant_or_commentdead_code",
          type: "bool",
          title: "No redundant code or commented-out functionality.",
        },
        {
          key: "no_redundant_or_commentdead_code_comment",
          type: "string",
          title: "Notes (optional)",
        },
        {
          key: "addresses_from_registry_or_constant",
          type: "bool",
          title:
            "Addresses must be fetched from the relevant protocol's address registry (e.g., grove-address-registry) if they are present there; otherwise they must be defined as constant and have a trusted source (e.g., when onboarding new contracts).",
        },
        {
          key: "addresses_from_registry_or_constant_comment",
          type: "string",
          title: "Notes (optional)",
        },
        {
          key: "address_rows",
          type: "item_list",
          title: "List every address used in the spell (defined as constant or fetched from the registry repo (e.g. 0x80ac24aA929eaF5013f6436cdA2a7ba190f5Cc0b):",
          subInputs: [
            {
              key: "registry_label",
              type: "string",
              title: "Name (e.g. [Ethereum.SYRUP_USDC])",
            },
            {
              key: "source_url",
              type: "string",
              title: "Source URL (forum, docs, chainlog, etc.)",
            },
            {
              key: "matches_valid_external_source",
              type: "bool",
              title:
                "Matches valid external source (previously approved forum post, external docs, etc).",
            },
            {
              key: "comment",
              type: "string",
              title: "Notes (optional)",
            },
          ],
        },
      ],
    },
    {
      key: "spell_starguard",
    type: "input",
    title: "StarGuard execution",
    permissions: [],
    nextStepKey: "spell_new_contracts",
    inputs: [
      {
        key: "sg_onboarded",
        type: "bool",
        title:
          "If a [StarGuard module](https://github.com/sky-ecosystem/star-guard) is onboarded for this Star, the following additional checks are done:",
      },
      { key: "sg_onboarded_comment", type: "string", title: "Notes (optional)" },
      {
        key: "sg_executable_view",
        type: "bool",
        title:
          "The spell exposes view-only interface `function isExecutable() external view returns (bool result)`",
      },
      { key: "sg_executable_view_comment", type: "string", title: "Notes (optional)" },
      {
        key: "sg_executable_logic_ok",
        type: "bool",
        title:
          "`isExecutable` either simply returns `true` or implements additional logic communicated via the relevant forum post (e.g., by describing \"earliest launch date\" or \"office hours\" logic, etc)",
      },
      { key: "sg_executable_logic_comment", type: "string", title: "Notes (optional)" },
      {
        key: "sg_test_executable_before_expiry",
        type: "bool",
        title:
          "The test ensures the spell is executable before expiration (i.e. `isExecutable` outputs `true` before `StarGuard.maxDelay()` is passed)",
      },
      {
        key: "sg_test_executable_before_expiry_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "sg_third_party_later_block",
        type: "bool",
        title:
          "Third-party actors can not take advantage of the fact that Spell will be executed in a later block than the Core spell, otherwise suggest `direct execution`",
      },
      { key: "sg_third_party_later_block_comment", type: "string", title: "Notes (optional)" },
      {
        key: "sg_sequential_forum_direct_exec",
        type: "bool",
        title:
          "If the Agent spell can't be executed in a later block OR have to be executed sequentially to another Star spell, `direct execution` is clearly mentioned in the forum post together with elaborated explanation why it is needed",
      },
      {
        key: "sg_sequential_forum_direct_exec_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "sg_direct_exec_explanation",
        type: "bool",
        title:
          "The `direct execution` explanation makes sense on the technical level and can not be circumvented by the use of `isExecutable()` interface",
      },
      { key: "sg_direct_exec_explanation_comment", type: "string", title: "Notes (optional)" },
    ],
  },
  {
    key: "spell_new_contracts",
    type: "input",
    title: "On-boarding new contracts",
    permissions: [],
    nextStepKey: "spell_dependency_checks",
    inputs: [
      {
        key: "new_contract_rows",
        type: "item_list",
        title: "List every new contract present in the spell (e.g. 0xbd34fc6AAa1d3F52B314CB9D78023dd23eAc3B0E):",
        subInputs: [
          {
            key: "contract_heading",
            type: "string",
            title: "Heading (e.g. [Ethereum] `ALLOCATOR_VAULT`)",
          },
          {
            key: "source_explorer_verified",
            type: "bool",
            title: "Source verified on Etherscan / primary explorer.",
          },
          { key: "source_explorer_verified_comment", type: "string", title: "Notes (optional)" },
          {
            key: "source_matches_audited_repo",
            type: "bool",
            title: "Source matches audited GitHub source.",
          },
          { key: "source_matches_audited_repo_comment", type: "string", title: "Notes (optional)" },
          {
            key: "compilation_matches_repo",
            type: "bool",
            title: "Compilation optimizations match deployment settings defined in the source code repo",
          },
          { key: "compilation_matches_repo_comment", type: "string", title: "Notes (optional)" },
          { key: "consistent_license", type: "bool", title: "Consistent license." },
          { key: "consistent_license_comment", type: "string", title: "Notes (optional)" },
          {
            key: "constructor_parameters",
            type: "item_list",
            title:
              "List every constructor argument",
              subInputs: [
                {
                  key: "argument_value",
                  type: "string",
                  title: "Argument value",
                },
                {
                  key: "argument_value_valid_external_source",
                  type: "string",
                  title: "Argument value matches valid external source"
                }]
          },
        ],
      },
    ],
  },
  {
    key: "spell_dependency_checks",
    type: "input",
    title: "Dependency checks",
    permissions: [],
    nextStepKey: "spell_interfaces",
    inputs: [
      {
        key: "submodule_listing",
        type: "item_list",
        title: "List every submodule or any other imported code used in this spell (e.g. lib/dss-allocator): ",
        subInputs: [
          {
            key: "commit",
            type: "string",
            title: "Commit",
          },
          {
            key: "commit_match",
            type: "bool",
            title: "The dependency commit matches audited commit",
          },
          {
            key: "commit_match_deployment",
            type: "bool",
            title: "The dependency commit matches the version of the deployed contracts",
          },
          {
            key: "commit_match_deployment_comment",
            type: "string",
            title: "Notes (optional)",
          },
        ],
      },
    ],
  },
  {
    key: "spell_interfaces",
    type: "input",
    title: "Interfaces",
    permissions: [],
    nextStepKey: "spell_variable_declarations",
    inputs: [
      { key: "intf_no_unused_static", type: "bool", title: "No unused static interfaces." },
      { key: "intf_no_unused_static_comment", type: "string", title: "Notes (optional)" },
      {
        key: "intf_stdlib_or_import",
        type: "bool",
        title:
          "Declared static interface not in standard libraries, OR imported from there.",
      },
      { key: "intf_stdlib_or_import_comment", type: "string", title: "Notes (optional)" },
      {
        key: "intf_matches_deployed",
        type: "bool",
        title: "Interface matches the deployed contract.",
      },
      { key: "intf_matches_deployed_comment", type: "string", title: "Notes (optional)" },
      {
        key: "intf_only_used_functions",
        type: "bool",
        title: "Each static interface declares only functions used in the spell.",
      },
      { key: "intf_only_used_functions_comment", type: "string", title: "Notes (optional)" },
    ],
  },
  {
    key: "spell_variable_declarations",
    type: "input",
    title: "Variable declarations",
    permissions: [],
    nextStepKey: "spell_deployment_security",
    inputs: [
      {
        key: "vd_constants_or_immutable",
        type: "bool",
        title: "Every contract variable is `constant` or `immutable`.",
      },
      { key: "vd_constants_or_immutable_comment", type: "string", title: "Notes (optional)" },
      {
        key: "vd_precision_literals_ok",
        type: "bool",
        title: "Precision variables (`WAD`, `RAY`, `RAD`, etc.) match expected values.",
      },
      { key: "vd_precision_literals_ok_comment", type: "string", title: "Notes (optional)" },
      {
        key: "precision_variable_rows",
        type: "item_list",
        title: "List every variable using precision (`e18`, `e6`, `e...`, `WAD`, `RAY`, `RAD`, etc):",
        subInputs: [
          {
            key: "precision_text",
            type: "string",
            title: "Precision (e.g. 100_000_000e18)",
          },
          {
            key: "precision_url",
            type: "string",
            title: "Source URL",
          },
          {
            key: "precision_matches_source",
            type: "bool",
            title: "Precision matches provided source URL.",
          },
          { key: "comment", type: "string", title: "Notes (optional)" },
        ],
      },
      {
        key: "vd_rates_slash_days_ok",
        type: "bool",
        title: "Rates expressed correctly (e.g. per `/ 1 days`).",
      },
      { key: "vd_rates_slash_days_comment", type: "string", title: "Notes (optional)" },
      {
        key: "vd_rates_match_source",
        type: "bool",
        title: "Rates match their source (e.g. governance poll).",
      },
      { key: "vd_rates_match_source_comment", type: "string", title: "Notes (optional)" },
      {
        key: "vd_timestamps_utc_ok",
        type: "bool",
        title: "Timestamps commented with full UTC date and convert correctly.",
      },
      { key: "vd_timestamps_utc_comment", type: "string", title: "Notes (optional)" },
      {
        key: "vd_timestamps_match_source",
        type: "bool",
        title: "Timestamps match their source (e.g. governance poll).",
      },
      { key: "vd_timestamps_match_source_comment", type: "string", title: "Notes (optional)" },
    ],
  },
  {
    key: "spell_deployment_security",
    type: "input",
    title: "Deployment & execution security",
    permissions: [],
    nextStepKey: "spell_access_control",
    inputs: [
      { key: "ds_no_selfdestruct", type: "bool", title: "No `selfdestruct()` in the spell." },
      { key: "ds_no_selfdestruct_comment", type: "string", title: "Notes (optional)" },
      {
        key: "ds_no_delegatecall_untrusted",
        type: "bool",
        title: "No `delegatecall()` to untrusted contracts.",
      },
      { key: "ds_no_delegatecall_untrusted_comment", type: "string", title: "Notes (optional)" },
      {
        key: "ds_no_tx_origin_auth",
        type: "bool",
        title: "No `tx.origin` for authorization.",
      },
      { key: "ds_no_tx_origin_auth_comment", type: "string", title: "Notes (optional)" },
      {
        key: "ds_no_external_revert_spell",
        type: "bool",
        title: "No external calls that could revert and fail the whole spell.",
      },
      {
        key: "ds_no_external_revert_spell_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "ds_no_unbounded_loops",
        type: "bool",
        title: "No loops with unbounded gas consumption.",
      },
      { key: "ds_no_unbounded_loops_comment", type: "string", title: "Notes (optional)" },
      {
        key: "ds_no_timestamp_gsm_issues",
        type: "bool",
        title: "No timestamp-dependent logic problematic across GSM delay.",
      },
      {
        key: "ds_no_timestamp_gsm_issues_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "ds_safe_math_or_checked",
        type: "bool",
        title: "Math uses safe libraries or overflow/underflow is checked.",
      },
      { key: "ds_safe_math_or_checked_comment", type: "string", title: "Notes (optional)" },
      {
        key: "ds_no_ignored_return_values",
        type: "bool",
        title: "No unchecked return values from external calls.",
      },
      {
        key: "ds_no_ignored_return_values_comment",
        type: "string",
        title: "Notes (optional)",
      },
    ],
  },
  {
    key: "spell_access_control",
    type: "input",
    title: "Access control",
    permissions: [],
    nextStepKey: "spell_parameter_protocol",
    inputs: [
      {
        key: "ac_no_frontrun_execution",
        type: "bool",
        title: "Spell execution cannot be front-run by malicious actors.",
      },
      { key: "ac_no_frontrun_execution_comment", type: "string", title: "Notes (optional)" },
      {
        key: "ac_no_unauthorized_privileged",
        type: "bool",
        title: "No privileged functions accessible by unauthorized users.",
      },
      { key: "ac_privileged_comment", type: "string", title: "Notes (optional)" },
    ],
  },
  {
    key: "spell_parameter_protocol",
    type: "input",
    title: "Parameter changes & protocol integration",
    permissions: [],
    nextStepKey: "spell_testing_review",
    inputs: [
      {
        key: "pp_star_invariants",
        type: "bool",
        title: "Star Protocol invariants maintained after spell execution.",
      },
      { key: "pp_star_invariants_comment", type: "string", title: "Notes (optional)" },
      {
        key: "pp_helpers_used",
        type: "bool",
        title: "Parameter changes use appropriate helper functions when available.",
      },
      { key: "pp_helpers_used_comment", type: "string", title: "Notes (optional)" },
      {
        key: "pp_matches_executive_or_atlas",
        type: "bool",
        title: "Parameter changes match Executive Sheet or corresponding Atlas edit.",
      },
      {
        key: "pp_matches_executive_or_atlas_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "pp_protocol_integration_ok",
        type: "bool",
        title: "Spell interacts correctly with existing protocol components.",
      },
      {
        key: "pp_protocol_integration_ok_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "pp_error_handling_ok",
        type: "bool",
        title: "Proper error handling for all external interactions.",
      },
      { key: "pp_error_handling_ok_comment", type: "string", title: "Notes (optional)" },
    ],
  },
  {
    key: "spell_testing_review",
    type: "input",
    title: "Testing",
    permissions: [],
    nextStepKey: "spell_pre_deployment",
    inputs: [
      {
        key: "spell_action_test_rows",
        type: "item_list",
        title: "List each spell action (each line of code which changes a storage):",
        subInputs: [
          {
            key: "unit_test_value_changed",
            type: "bool",
            title: "The unit test ensures the new value was changed in the spell",
          },
          { key: "unit_test_comment", type: "string", title: "Notes (optional)" },
          {
            key: "e2e_test_sufficient",
            type: "bool",
            title: "The end-to-end test is sufficient to ensure correctness the high-level goal behind this spell action",
          },
          { key: "e2e_test_comment", type: "string", title: "Notes (optional)" },
        ],
      },
      {
        key: "test_all_actions_covered",
        type: "bool",
        title: "All actions are covered by tests.",
      },
      { key: "test_all_actions_covered_comment", type: "string", title: "Notes (optional)" },
      {
        key: "test_integration_flow",
        type: "bool",
        title: "Integration tests verify end-to-end execution flow.",
      },
      { key: "test_integration_flow_comment", type: "string", title: "Notes (optional)" },
      {
        key: "test_gas_within_block_limit",
        type: "bool",
        title: "Gas tests ensure execution fits within block gas limit.",
      },
      {
        key: "test_gas_within_block_limit_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "test_ci_passing_at_sha",
        type: "bool",
        title: "All tests passing in CI at referenced commit (see notes for link/sha).",
      },
      { key: "test_ci_passing_comment", type: "string", title: "CI / commit notes (optional)" },
      {
        key: "test_none_skipped",
        type: "bool",
        title: "Tests listed above are not `skipped`.",
      },
      { key: "test_none_skipped_comment", type: "string", title: "Notes (optional)" },
      {
        key: "test_local_passing",
        type: "bool",
        title: "All tests passing locally (see output block).",
      },
      {
        key: "test_local_output_block",
        type: "string-multiline",
        title: "Local test output",
      },
      {
        key: "test_post_output_comment",
        type: "string",
        title: "Notes after local output (e.g. compiler warnings)",
      },
    ],
  },
  {
    key: "spell_pre_deployment",
    type: "input",
    title: "Pre-deployment checks",
    permissions: [],
    nextStepKey: null,
    inputs: [
      {
        key: "pre_exec_sheet_matches_scope",
        type: "bool",
        title:
          "Actions listed in the Executive Sheet for this Star match the spell scope.",
      },
      {
        key: "pre_exec_sheet_matches_scope_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "pre_exec_sheet_not_ready_alt",
        type: "bool",
        title:
          "IF Executive Sheet is not yet ready at review, reference the corresponding Atlas edit weekly proposal and the forum post (nested checklist).",
      },
      {
        key: "pre_exec_sheet_not_ready_alt_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "pre_instruction_text_in_spell",
        type: "bool",
        title:
          "Every Instruction text from the Executive Sheet is copied to the spell code as a comment.",
      },
      {
        key: "pre_instruction_text_in_spell_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "pre_instruction_not_ready_alt",
        type: "bool",
        title:
          "IF Executive Sheet is not yet ready at review, reference the corresponding Atlas edit weekly proposal and the forum post (nested checklist).",
      },
      {
        key: "pre_instruction_not_ready_alt_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "pre_instruction_cannot_note",
        type: "bool",
        title:
          "IF an instruction cannot be taken, it has an explanation under the instruction prefixed with // Note:.",
      },
      {
        key: "pre_instruction_cannot_note_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "pre_unlisted_action_note",
        type: "bool",
        title:
          "IF an action in the spell does not have a relevant instruction, its necessity is explained in a comment prefixed with // Note:.",
      },
      {
        key: "pre_unlisted_action_note_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "pre_spell_in_exec_sheet",
        type: "bool",
        title:
          "All actions present in the spell code are present in the final Executive Sheet.",
      },
      {
        key: "pre_spell_in_exec_sheet_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "pre_spell_in_sheet_not_ready_alt",
        type: "bool",
        title:
          "IF Executive Sheet is not yet ready at review, reference the corresponding Atlas edit weekly proposal and the forum post (nested checklist).",
      },
      {
        key: "pre_spell_in_sheet_not_ready_alt_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "pre_exec_sheet_in_spell",
        type: "bool",
        title:
          "All actions in the final Executive Sheet are present in the spell code.",
      },
      {
        key: "pre_exec_sheet_in_spell_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "pre_exec_sheet_in_spell_not_ready_alt",
        type: "bool",
        title:
          "IF Executive Sheet is not yet ready at review, reference the corresponding Atlas edit weekly proposal and the forum post (nested checklist).",
      },
      {
        key: "pre_exec_sheet_in_spell_not_ready_alt_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "pre_reverified_after_commits",
        type: "bool",
        title:
          "IF new commits were added after the initial review, the relevant checklist items have been re-verified.",
      },
      {
        key: "pre_reverified_after_commits_comment",
        type: "string",
        title: "Notes (optional)",
      },
      {
        key: "pre_good_to_deploy_post",
        type: "bool",
        title:
          "IF no blockers were found, post the completed Development Stage checklist with an explicit Good to deploy note on top.",
      },
      {
        key: "pre_good_to_deploy_post_comment",
        type: "string",
        title: "Notes (optional)",
      },
    ],
  },

  ],
  resultViewControls: [
    {
      title: "Handoff markdown",
      plainText: true,
      data: AGENT_SPELL_REVIEW_HANDOFF_RESULT_DATA,
    },
  ],
};
