import type { Template } from "@/entities/template";

/**
 * Single `{{ … }}` block for result view resolution (must not contain `}}` before the closing delimiter).
 */
const AGENT_SPELL_REVIEW_HANDOFF_RESULT_DATA = [
  "{{ (() => {",
  "  try {",
  "    const BR = String.fromCharCode(10);",
  "    const step = spell_review;",
  '    if (!step || typeof step !== "object" || Array.isArray(step)) return "";',
  "    const prs = Array.isArray(step.prs) ? step.prs : [];",
  "    const lines = [];",
  '    lines.push("### Development Stage");',
  '    lines.push("");',
  '    lines.push("#### Preparation");',
  '    lines.push("- LIST every commit since the last externally reviewed spell:");',
  "    const esc = (s) => String(s).split(String.fromCharCode(96)).join(String.fromCharCode(39));",
  "    const shortFromUrl = (u) => {",
  "      const s = String(u);",
  '      const ix = s.toLowerCase().indexOf("/commit/");',
  '      if (ix < 0) return "unknown";',
  '      const hex = s.slice(ix + 8).replace(/[^a-fA-F0-9].*/, "");',
  '      return hex.slice(0, 7) || "unknown";',
  "    };",
  "    for (const row of prs) {",
  '      if (!row || typeof row !== "object") continue;',
  "      const r = row;",
  '      const url = String(r.value ?? r.commit_url ?? "").trim();',
  "      const has =",
  "        url ||",
  "        r.content_matches_description === true ||",
  "        r.no_security_changes === true ||",
  '        String(r.comment ?? "").trim();',
  "      if (!has) continue;",
  '      const short = url ? shortFromUrl(url) : "_______";',
  '      const safe = url',
  '        .replace(/\\(/g, "%28")',
  '        .replace(/\\)/g, "%29")',
  '        .replace(/ /g, "%20");',
  '      const link = url ? "[open commit](" + safe + ")" : "(no URL)";',
  '      lines.push("  - " + String.fromCharCode(96) + short + String.fromCharCode(96) + ", " + link);',
  "      const cm = r.content_matches_description === true;",
  '      lines.push("    - [" + (cm ? "x" : " ") + "] Content matches description: no unrelated changes.");',
  '      const com = String(r.comment ?? "").trim();',
  "      if (com) {",
  "        const parts = com.split(/[\\r\\n]+/);",
  "        for (let i = 0; i < parts.length; i++) {",
  '          lines.push((i === 0 ? "      :information_source: " : "            ") + esc(parts[i]));',
  "        }",
  "      }",
  "      const ns = r.no_security_changes === true;",
  '      lines.push("    - [" + (ns ? "x" : " ") + "] No security-related changes are present in this commit.");',
  "    }",
  '    lines.push("");',
  "    const solc = step.solc_version_verified === true;",
  '    lines.push(',
  '      "- [" + (solc ? "x" : " ") + "] Verify solc version matches the Prime Agent protocol standard based on prior contracts."',
  "    );",
  '    const sc = String(step.solc_version_verified_comment ?? "").trim();',
  "    if (sc) {",
  "      const parts = sc.split(/[\\r\\n]+/);",
  "      for (let i = 0; i < parts.length; i++) {",
  '        lines.push((i === 0 ? "  :information_source: " : "        ") + esc(parts[i]));',
  "      }",
  "    }",
  '    lines.push("");',
  "    return lines.join(BR);",
  "  } catch (e) {",
  '    return "";',
  "  }",
  "})() }}",
].join("\n");

export const agentSpellReviewTemplate: Template = {
  key: "agent-spell-review",
  name: "Agent spell review",
  firstStepKey: "spell_review",
  permissions: [],
  steps: [
    {
      key: "spell_review",
      type: "input",
      title: "Review commit messages",
      permissions: [],
      nextStepKey: null,
      inputs: [
        {
          key: "prs",
          type: "item_list",
          title: "Github Commit URLs:",
          subInputs: [
            {
              key: "content_matches_description",
              type: "bool",
              title: "Content matches description",
            },
            {
              key: "no_security_changes",
              type: "bool",
              title: "No security-related changes are present in this commit.",
            },
            {
              key: "comment",
              type: "string",
              title: "Comment (optional)",
            },
          ],
        },
        {
          key: "solc_version_verified",
          type: "bool",
          title:
            "Verify solc version matches the Prime Agent protocol standard based on prior contracts.",
        },
        {
          key: "solc_version_verified_comment",
          type: "string",
          title: "Comment (optional)",
        },
      ],
    },
  ],
  resultViewControls: [
    {
      title: "Handoff markdown",
      plainText: true,
      data: AGENT_SPELL_REVIEW_HANDOFF_RESULT_DATA,
    },
  ],
};
