import type { Template } from "@/entities/template";

export const nfatDepositRequestTemplate: Template = {
  key: "nfat-deposit-request",
  name: "NFAT Deposit Request",
  firstStepKey: "input_submit",
  allowedRoles: ["Prime"],
  steps: [
    {
      key: "input_submit",
      type: "input",
      title: "Submit Deposit Request",
      allowedRoles: ["Prime"],
      nextStepKey: "input_halo_review",
      confirmationMessage: "Your deposit request has been submitted. A Halo operator will review it shortly.",
      inputs: [
        {
          key: "facilityId",
          type: "string",
          title: "Facility ID",
        },
        {
          key: "depositAmount",
          type: "number",
          title: "Deposit Amount",
        },
        {
          key: "primeSignature",
          type: "string",
          title: "Prime Signature (optional — hex signature proving intent)",
        },
        {
          key: "hasCustomTerms",
          type: "bool",
          title: "Request custom terms (override facility buy box)?",
        },
        {
          key: "terms_description",
          type: "string",
          title: "Custom Terms: Description",
          visibleExpression: "input_submit.hasCustomTerms === true",
        },
        {
          key: "terms_loanSizeMin",
          type: "number",
          title: "Custom Terms: Loan Size Min",
          visibleExpression: "input_submit.hasCustomTerms === true",
        },
        {
          key: "terms_loanSizeMax",
          type: "number",
          title: "Custom Terms: Loan Size Max",
          visibleExpression: "input_submit.hasCustomTerms === true",
        },
        {
          key: "terms_durationMinDays",
          type: "number",
          title: "Custom Terms: Duration Min (days)",
          visibleExpression: "input_submit.hasCustomTerms === true",
        },
        {
          key: "terms_durationMaxDays",
          type: "number",
          title: "Custom Terms: Duration Max (days)",
          visibleExpression: "input_submit.hasCustomTerms === true",
        },
        {
          key: "terms_rateMinBps",
          type: "number",
          title: "Custom Terms: Rate Min (bps)",
          visibleExpression: "input_submit.hasCustomTerms === true",
        },
        {
          key: "terms_rateMaxBps",
          type: "number",
          title: "Custom Terms: Rate Max (bps)",
          visibleExpression: "input_submit.hasCustomTerms === true",
        },
      ],
    },
    {
      key: "input_halo_review",
      type: "input",
      title: "Halo Review",
      allowedRoles: ["Halo"],
      nextStepKey: "condition_halo_decision",
      inputs: [
        {
          key: "_view_facility",
          type: "string",
          title: "Facility ID",
          readOnly: true,
          defaultValue: "${input_submit.facilityId}",
        },
        {
          key: "_view_amount",
          type: "string",
          title: "Deposit Amount",
          readOnly: true,
          defaultValue: "${input_submit.depositAmount}",
        },
        {
          key: "_view_signature",
          type: "string",
          title: "Prime Signature",
          readOnly: true,
          defaultValue: "${input_submit.primeSignature}",
        },
        {
          key: "_view_custom_terms",
          type: "string",
          title: "Custom Terms Requested",
          readOnly: true,
          defaultValue: "${input_submit.hasCustomTerms}",
        },
        {
          key: "_view_terms_description",
          type: "string",
          title: "Custom Terms: Description",
          readOnly: true,
          defaultValue: "${input_submit.terms_description}",
          visibleExpression: "input_submit.hasCustomTerms === true",
        },
        {
          key: "_view_terms_loan_size",
          type: "string",
          title: "Custom Terms: Loan Size (min / max)",
          readOnly: true,
          defaultValue: "{{ input_submit.terms_loanSizeMin + ' / ' + input_submit.terms_loanSizeMax }}",
          visibleExpression: "input_submit.hasCustomTerms === true",
        },
        {
          key: "_view_terms_duration",
          type: "string",
          title: "Custom Terms: Duration days (min / max)",
          readOnly: true,
          defaultValue: "{{ input_submit.terms_durationMinDays + ' / ' + input_submit.terms_durationMaxDays }}",
          visibleExpression: "input_submit.hasCustomTerms === true",
        },
        {
          key: "_view_terms_rate",
          type: "string",
          title: "Custom Terms: Rate bps (min / max)",
          readOnly: true,
          defaultValue: "{{ input_submit.terms_rateMinBps + ' / ' + input_submit.terms_rateMaxBps }}",
          visibleExpression: "input_submit.hasCustomTerms === true",
        },
        {
          key: "accepted",
          type: "bool",
          title: "Accept this deposit request?",
        },
        {
          key: "rejectionReason",
          type: "string-multiline",
          title: "Rejection Reason",
          visibleExpression: "input_halo_review.accepted === false",
        },
      ],
    },
    {
      key: "condition_halo_decision",
      type: "condition",
      title: "Halo Decision",
      expression: "input_halo_review.accepted === true",
      thenStepKey: "input_govops_review",
      elseStepKey: "input_rejected_by_halo",
      nextStepKey: null,
    },
    {
      key: "input_govops_review",
      type: "input",
      title: "GovOps Review",
      allowedRoles: ["GovOps"],
      nextStepKey: "condition_govops_decision",
      inputs: [
        {
          key: "_view_facility",
          type: "string",
          title: "Facility ID",
          readOnly: true,
          defaultValue: "${input_submit.facilityId}",
        },
        {
          key: "_view_amount",
          type: "string",
          title: "Deposit Amount",
          readOnly: true,
          defaultValue: "${input_submit.depositAmount}",
        },
        {
          key: "_view_halo_accepted",
          type: "string",
          title: "Halo Decision",
          readOnly: true,
          defaultValue: "Accepted",
        },
        {
          key: "approved",
          type: "bool",
          title: "Approve this deposit request for on-chain execution?",
        },
        {
          key: "rejectionReason",
          type: "string-multiline",
          title: "Rejection Reason",
          visibleExpression: "input_govops_review.approved === false",
        },
        {
          key: "reviewNotes",
          type: "string-multiline",
          title: "Review Notes (internal)",
        },
      ],
    },
    {
      key: "condition_govops_decision",
      type: "condition",
      title: "GovOps Decision",
      expression: "input_govops_review.approved === true",
      thenStepKey: "input_execute",
      elseStepKey: "input_rejected_by_govops",
      nextStepKey: null,
    },
    {
      key: "input_execute",
      type: "input",
      title: "Record On-Chain Execution",
      allowedRoles: ["GovOps"],
      nextStepKey: null,
      inputs: [
        {
          key: "_view_facility",
          type: "string",
          title: "Facility ID",
          readOnly: true,
          defaultValue: "${input_submit.facilityId}",
        },
        {
          key: "_view_amount",
          type: "string",
          title: "Deposit Amount",
          readOnly: true,
          defaultValue: "${input_submit.depositAmount}",
        },
        {
          key: "txHash",
          type: "string",
          title: "Transaction Hash (on-chain execution)",
        },
      ],
    },
    {
      key: "input_rejected_by_halo",
      type: "input",
      title: "Rejected by Halo",
      allowedRoles: ["Prime"],
      nextStepKey: null,
      inputs: [
        {
          key: "_view_reason",
          type: "string",
          title: "Rejection Reason from Halo",
          readOnly: true,
          defaultValue: "${input_halo_review.rejectionReason}",
        },
        {
          key: "acknowledged",
          type: "bool",
          title: "I acknowledge this deposit request has been rejected",
        },
      ],
    },
    {
      key: "input_rejected_by_govops",
      type: "input",
      title: "Rejected by GovOps",
      allowedRoles: ["Prime"],
      nextStepKey: null,
      inputs: [
        {
          key: "_view_reason",
          type: "string",
          title: "Rejection Reason from GovOps",
          readOnly: true,
          defaultValue: "${input_govops_review.rejectionReason}",
        },
        {
          key: "_view_notes",
          type: "string",
          title: "Review Notes",
          readOnly: true,
          defaultValue: "${input_govops_review.reviewNotes}",
        },
        {
          key: "acknowledged",
          type: "bool",
          title: "I acknowledge this deposit request has been rejected",
        },
      ],
    },
  ],
  resultViewControls: [
    { data: "${input_submit.facilityId}", title: "Facility ID" },
    { data: "${input_submit.depositAmount}", title: "Deposit Amount" },
    { data: "${input_execute.txHash}", title: "Transaction Hash" },
  ],
};
